name = "kemureco"
compatibility_date = "2024-05-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# NEXT_PUBLIC_SUPABASE_URL = ""
# NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
